### ISSUE TITLE
Fix typos in README.md

### ISSUE THREAD

**Issue by hind-sagar-biswas** [hind-sagar-biswas/php_launcher#3]
Readme.md was recently updated and contains typos. Fix those.

**Comment by devharsh007** [comment]
I would like to work on it ... please assign it to me.  If you could add hacktoberfest pls do dat! it'll be beneficial to me.

**Comment by hind-sagar-biswas** [comment]
Some more instructions: 

1. The installation part will be renamed to Getting started
2. It will be moved bellow table of contents and add it to the table of contents
3. The current installation procedure will be changed by the bellow code:

```markdown
We have our own installer software which eases the installation process via which you can get started with your projects with a few clicks. The installer is called [PL Installer](https://github.com/hind-sagar-biswas/pl_installer). Go to the repo, then go to [Releases](https://github.com/hind-sagar-biswas/pl_installer/releases) and download binary from the latest release. After downloading, just run it and follow the instructions and you are done!
```

**Comment by devharsh007** [comment]
Thanks, will push tomorrow morning.
